# Generated by Django 3.1.2 on 2020-10-23 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201022_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='collection_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='img3',
        ),
    ]
