# Generated by Django 3.1.2 on 2020-11-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shoppageorderable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppageorderable',
            old_name='designItems',
            new_name='product',
        ),
    ]
