# Generated by Django 3.1.2 on 2020-11-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201117_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppage',
            name='collectionTag',
            field=models.CharField(default='wlias', max_length=1000),
            preserve_default=False,
        ),
    ]
