# Generated by Django 3.1.2 on 2020-11-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shoppage_collectiontag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppage',
            old_name='collectionTag',
            new_name='collection',
        ),
    ]
