# Generated by Django 3.1.2 on 2020-11-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='order_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
